#!/usr/bin/env bash
# map-repo.sh - generate/refresh an AGENTS.md workspace map for a repo or workspace,
# SCOPED to the parts you actually own (git history), with the HAND block seeded from
# your matching Claude Code skills. Portable: bash + git + coreutils, ZERO install.
#
#   map-repo.sh [DIR]      (re)write DIR/AGENTS.md            (default DIR = .)
#   map-repo.sh --check    exit 1 if AGENTS.md is stale       (CI / pre-commit gate)
#   map-repo.sh --full     ignore ownership scope; map all
#   map-repo.sh --stdout   print, don't write                 (preview)
#
# Levels: run it at a workspace root (parent of several repos) -> a global map that
# lists+links them; run it inside a repo -> that repo's map scoped to your dirs.
set -uo pipefail

CHECK=0; FULL=0; STDOUT=0; TARGET="."
for a in "$@"; do
  case "$a" in
    --check) CHECK=1 ;;
    --full) FULL=1 ;;
    --stdout|--dry) STDOUT=1 ;;
    -*) ;;
    *) TARGET="$a" ;;
  esac
done
command -v git >/dev/null 2>&1 || { echo "map-repo: git required" >&2; exit 2; }
cd "$TARGET" 2>/dev/null || { echo "map-repo: no such dir: $TARGET" >&2; exit 2; }

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
NAME="$(basename "$ROOT")"
SKILL_DIRS=("$HOME/.claude/skills" ".claude/skills")
SKIP='node_modules|dist|build|vendor|tmp'
skip_dir() { case "$1" in .*) return 0;; esac; echo "$1" | grep -qE "^($SKIP)$"; }

# --- ownership scope: top-level paths you've committed to (empty => no filter) ---
me="$(git config user.email 2>/dev/null)"; [ -z "$me" ] && me="$(git config user.name 2>/dev/null)"
owned=""
if [ "$FULL" = 0 ] && [ -n "$me" ]; then
  owned="$(git log --all --author="$me" --pretty=format: --name-only 2>/dev/null | sed '/^$/d; s#/.*##' | sort -u)"
fi
owns() { [ "$FULL" = 1 ] && return 0; [ -z "$owned" ] && return 0; printf '%s\n' "$owned" | grep -qxF "$1"; }

is_proj() { [ -e "$1/package.json" ] || [ -e "$1/go.mod" ] || [ -e "$1/Cargo.toml" ] || [ -e "$1/pyproject.toml" ] || [ -e "$1/.git" ]; }
stack_of() {
  if   [ -f "$1/pnpm-lock.yaml" ]; then echo pnpm
  elif [ -f "$1/package.json" ];   then echo npm
  elif [ -f "$1/go.mod" ];         then echo Go
  elif [ -f "$1/Cargo.toml" ];     then echo Rust
  elif [ -f "$1/pyproject.toml" ]; then echo Python
  else echo "-"; fi
}
ver_of() { sed -n 's/.*"version"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$1/package.json" 2>/dev/null | head -1; }
purpose_of() {
  local p=""
  [ -f "$1/README.md" ] && p="$(grep -m1 -E '^[A-Za-z]' "$1/README.md" 2>/dev/null | cut -c1-80)"
  [ -z "$p" ] && p="$(sed -n 's/.*"description"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$1/package.json" 2>/dev/null | head -1 | cut -c1-80)"
  printf '%s' "${p:--}"
}

units=()
for d in */; do d="${d%/}"; skip_dir "$d" && continue; is_proj "$d" && units+=("$d"); done

# --- HAND: preserve an existing block, else seed from matching skills, else stub ---
inner_hand() { [ -f AGENTS.md ] && awk '/<!-- HAND/{f=1;next} /<!-- \/HAND/{f=0} f{print}' AGENTS.md; }
seed_from_skills() {
  local s desc base
  for sd in "${SKILL_DIRS[@]}"; do [ -d "$sd" ] || continue
    for s in "$sd"/*/SKILL.md "$sd"/*.md; do [ -f "$s" ] || continue
      grep -qiw "$NAME" "$s" 2>/dev/null || continue
      base="$(basename "$(dirname "$s")")"; [ "$base" = "skills" ] && base="$(basename "$s" .md)"
      desc="$(sed -n 's/^description:[[:space:]]*//p' "$s" | head -1 | cut -c1-140)"
      [ -z "$desc" ] && desc="$(grep -m1 -E '^[A-Za-z*#]' "$s" 2>/dev/null | sed 's/^#* *//; s/\*//g' | cut -c1-140)"
      echo "- Skill \`$base\`: $desc"
    done
  done
}
hand_block() {
  echo "<!-- HAND (facts a scan can't infer; edit by hand) -->"
  local eh; eh="$(inner_hand)"
  if [ -n "$eh" ]; then printf '%s\n' "$eh"
  else
    local seeded; seeded="$(seed_from_skills)"
    if [ -n "$seeded" ]; then echo "- _Seeded from your skills - edit/expand:_"; printf '%s\n' "$seeded"
    else echo "- TODO: what this repo/workspace is, where YOUR part lives, the key entry points."; fi
  fi
  echo "<!-- /HAND -->"
}

gen_block() {
  echo "<!-- GEN (generated by map-repo.sh from disk + git ownership; do not hand-edit) -->"
  if [ ${#units[@]} -gt 0 ]; then
    echo "| Area | Purpose | Ver | Stack | Yours |"
    echo "|------|---------|-----|-------|-------|"
    for u in "${units[@]}"; do
      local mine=no; owns "$u" && mine=yes
      [ "$FULL" = 0 ] && [ -n "$owned" ] && [ "$mine" = no ] && continue
      printf '| %s | %s | %s | %s | %s |\n' "$u" "$(purpose_of "$u")" "$(ver_of "$u" || echo -)" "$(stack_of "$u")" "$mine"
    done
  else
    echo "_Single project \`$NAME\` ($(stack_of .)). Your areas:_"
    echo
    for d in */; do d="${d%/}"; skip_dir "$d" && continue
      [ "$FULL" = 0 ] && [ -n "$owned" ] && ! owns "$d" && continue
      echo "- \`$d/\`"
    done
  fi
  echo "<!-- /GEN -->"
}

render() {
  echo "# $NAME workspace map (AGENTS.md)"
  echo
  echo "Read this FIRST every session - it routes to what exists + your part, so you don't grep-storm."
  echo "Scoped to what you've committed to. Search: structural -> ast-grep (\`sg\`); text -> ripgrep (\`rg\`)."
  echo
  hand_block
  echo
  gen_block
}

if [ "$STDOUT" = 1 ]; then render; exit 0; fi
if [ "$CHECK" = 1 ]; then
  cur=""; [ -f AGENTS.md ] && cur="$(cat AGENTS.md)"
  if [ "$cur" = "$(render)" ]; then echo "[OK] AGENTS.md current"; exit 0
  else echo "[DRIFT] AGENTS.md stale - run: map-repo.sh" >&2; exit 1; fi
fi
render > AGENTS.md
echo "[OK] wrote $ROOT/AGENTS.md (units: ${#units[@]}, owned-filter: $([ -n "$owned" ] && echo on || echo off))"
